### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by SergiLomtadze**

### CODE REVIEW

**Review by kdavletov-exadel — CHANGES_REQUESTED** [review]
Use `.gitignore` to ignore `.vs` folder

**Review by kdavletov-exadel — CHANGES_REQUESTED** [review]
Your `.gitignore` is correct. That means next time any change under `.vs` folder will be ignored by git. 

However, before introducing this gitignore rule, you already had `.vs` folder in the branch. I forget to mention that you have to remove that as well. No worries, that is one-time job.

**Comment by SergiLomtadze** [comment]
> Your `.gitignore` is correct. That means next time any change under `.vs` folder will be ignored by git.
> 
> However, before introducing this gitignore rule, you already had `.vs` folder in the branch. I forget to mention that you have to remove that as well. No worries, that is one-time job.

Done

**Comment by SergiLomtadze** [comment]
> Use `.gitignore` to ignore `.vs` folder

Done

**Review by kdavletov-exadel — APPROVED** [review]

**Pull request merged**
