### PR TITLE
add Console,BA,DA layers with logic 

### LINKED ISSUE #3: create console app for task3

### PR DESCRIPTION
**Pull request by SergiLomtadze**
Closes #3

### CODE REVIEW

**Review by kdavletov-exadel — CHANGES_REQUESTED** [review]
gitignore `bin` and `obj` folders.

**Review by kdavletov-exadel — CHANGES_REQUESTED** [review]
`dotnet restore` step in the CI is trying to restore solution under `src` folder, but there is neither solution nor project files. `ExadelMentorship` subfolder is unneccesary. Move everything one level up and get rid of the subfolder. Then the CI will work as expected.

**Comment by kdavletov-exadel** [comment]
> closes #3
Use that in PR description, not the title. Give PR title meaningful name. Github does not scan PR title for autolinking an issue.

**Comment by SergiLomtadze** [comment]
> gitignore `bin` and `obj` folders.

done

**Comment by SergiLomtadze** [comment]
> `dotnet restore` step in the CI is trying to restore solution under `src` folder, but there is neither solution nor project files. `ExadelMentorship` subfolder is unneccesary. Move everything one level up and get rid of the subfolder. Then the CI will work as expected.

done

**Comment by SergiLomtadze** [comment]
closes #3

**Review by kdavletov-exadel — APPROVED** [review]

**Pull request merged**
